version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

sphinx:
  configuration: docs/conf.py

python:
   install:
      - method: pip
        path: .
        extra_requirements:
          - gevent
          - mongodb
          - redis
          - rethinkdb
          - sqlalchemy
          - tornado
          - twisted
          - zookeeper
          - doc
