version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest

sphinx:
  configuration: docs/conf.py

python:
   install:
      - method: pip
        path: .
        extra_requirements: [doc]
