services:
  postgresql:
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: secret

  mysql:
    image: mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: secret

  mongodb:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - type: bind
        source: ./tools/mongodb-init.sh
        target: /docker-entrypoint-initdb.d/mongodb-init.sh
        read_only: true
    environment:
      # https://forums.docker.com/t/docker-compose-mongo-exit-code-139/151353/10
      - GLIBC_TUNABLES=glibc.pthread.rseq=1

  emqx:
    image: emqx/emqx
    ports:
      - 127.0.0.1:1883:1883

  redis:
    image: redis
    ports:
      - 127.0.0.1:6379:6379
